//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EricssonConsoleApiTester.SubscriptionTraffic {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.dcp.ericsson.net/SubscriptionTraffic", ConfigurationName="SubscriptionTraffic.SubscriptionTraffic")]
    public interface SubscriptionTraffic {
        
        // CODEGEN: Generating message contract since the operation query is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://api.dcp.ericsson.net/session/query/query", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EricssonConsoleApiTester.SubscriptionTraffic.queryResponse1 query(EricssonConsoleApiTester.SubscriptionTraffic.queryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.dcp.ericsson.net/session/query/query", ReplyAction="*")]
        System.Threading.Tasks.Task<EricssonConsoleApiTester.SubscriptionTraffic.queryResponse1> queryAsync(EricssonConsoleApiTester.SubscriptionTraffic.queryRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.dcp.ericsson.net/SubscriptionTraffic")]
    public partial class query : object, System.ComponentModel.INotifyPropertyChanged {
        
        private resource resourceField;
        
        private int rangeField;
        
        private bool rangeFieldSpecified;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public resource resource {
            get {
                return this.resourceField;
            }
            set {
                this.resourceField = value;
                this.RaisePropertyChanged("resource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int range {
            get {
                return this.rangeField;
            }
            set {
                this.rangeField = value;
                this.RaisePropertyChanged("range");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rangeSpecified {
            get {
                return this.rangeFieldSpecified;
            }
            set {
                this.rangeFieldSpecified = value;
                this.RaisePropertyChanged("rangeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.dcp.ericsson.net/SubscriptionTraffic")]
    public partial class resource : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private resourceType typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public resourceType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.dcp.ericsson.net/SubscriptionTraffic")]
    public enum resourceType {
        
        /// <remarks/>
        imsi,
        
        /// <remarks/>
        msisdn,
        
        /// <remarks/>
        imei,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.dcp.ericsson.net/SubscriptionTraffic")]
    public partial class sms : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int countField;
        
        private bool countFieldSpecified;
        
        private string lastDestField;
        
        private System.DateTime lastSmsField;
        
        private bool lastSmsFieldSpecified;
        
        private int smsErrorCountField;
        
        private bool smsErrorCountFieldSpecified;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countSpecified {
            get {
                return this.countFieldSpecified;
            }
            set {
                this.countFieldSpecified = value;
                this.RaisePropertyChanged("countSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string lastDest {
            get {
                return this.lastDestField;
            }
            set {
                this.lastDestField = value;
                this.RaisePropertyChanged("lastDest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime lastSms {
            get {
                return this.lastSmsField;
            }
            set {
                this.lastSmsField = value;
                this.RaisePropertyChanged("lastSms");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastSmsSpecified {
            get {
                return this.lastSmsFieldSpecified;
            }
            set {
                this.lastSmsFieldSpecified = value;
                this.RaisePropertyChanged("lastSmsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int smsErrorCount {
            get {
                return this.smsErrorCountField;
            }
            set {
                this.smsErrorCountField = value;
                this.RaisePropertyChanged("smsErrorCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool smsErrorCountSpecified {
            get {
                return this.smsErrorCountFieldSpecified;
            }
            set {
                this.smsErrorCountFieldSpecified = value;
                this.RaisePropertyChanged("smsErrorCountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=4)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.dcp.ericsson.net/SubscriptionTraffic")]
    public partial class gprs : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool pdpActiveField;
        
        private bool pdpActiveFieldSpecified;
        
        private System.DateTime activationField;
        
        private bool activationFieldSpecified;
        
        private string ipField;
        
        private string apnField;
        
        private double txField;
        
        private bool txFieldSpecified;
        
        private System.DateTime lastTxField;
        
        private bool lastTxFieldSpecified;
        
        private double rxField;
        
        private bool rxFieldSpecified;
        
        private System.DateTime lastRxField;
        
        private bool lastRxFieldSpecified;
        
        private string giDestAddressField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool pdpActive {
            get {
                return this.pdpActiveField;
            }
            set {
                this.pdpActiveField = value;
                this.RaisePropertyChanged("pdpActive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pdpActiveSpecified {
            get {
                return this.pdpActiveFieldSpecified;
            }
            set {
                this.pdpActiveFieldSpecified = value;
                this.RaisePropertyChanged("pdpActiveSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime activation {
            get {
                return this.activationField;
            }
            set {
                this.activationField = value;
                this.RaisePropertyChanged("activation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activationSpecified {
            get {
                return this.activationFieldSpecified;
            }
            set {
                this.activationFieldSpecified = value;
                this.RaisePropertyChanged("activationSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ip {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
                this.RaisePropertyChanged("ip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string apn {
            get {
                return this.apnField;
            }
            set {
                this.apnField = value;
                this.RaisePropertyChanged("apn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double tx {
            get {
                return this.txField;
            }
            set {
                this.txField = value;
                this.RaisePropertyChanged("tx");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool txSpecified {
            get {
                return this.txFieldSpecified;
            }
            set {
                this.txFieldSpecified = value;
                this.RaisePropertyChanged("txSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public System.DateTime lastTx {
            get {
                return this.lastTxField;
            }
            set {
                this.lastTxField = value;
                this.RaisePropertyChanged("lastTx");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastTxSpecified {
            get {
                return this.lastTxFieldSpecified;
            }
            set {
                this.lastTxFieldSpecified = value;
                this.RaisePropertyChanged("lastTxSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double rx {
            get {
                return this.rxField;
            }
            set {
                this.rxField = value;
                this.RaisePropertyChanged("rx");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rxSpecified {
            get {
                return this.rxFieldSpecified;
            }
            set {
                this.rxFieldSpecified = value;
                this.RaisePropertyChanged("rxSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public System.DateTime lastRx {
            get {
                return this.lastRxField;
            }
            set {
                this.lastRxField = value;
                this.RaisePropertyChanged("lastRx");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastRxSpecified {
            get {
                return this.lastRxFieldSpecified;
            }
            set {
                this.lastRxFieldSpecified = value;
                this.RaisePropertyChanged("lastRxSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string giDestAddress {
            get {
                return this.giDestAddressField;
            }
            set {
                this.giDestAddressField = value;
                this.RaisePropertyChanged("giDestAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=9)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.dcp.ericsson.net/SubscriptionTraffic")]
    public partial class lastLu : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string gprsStatusField;
        
        private System.DateTime timestampField;
        
        private bool timestampFieldSpecified;
        
        private string countryCodeField;
        
        private string operatorCodeField;
        
        private string vlrGtField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string gprsStatus {
            get {
                return this.gprsStatusField;
            }
            set {
                this.gprsStatusField = value;
                this.RaisePropertyChanged("gprsStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timestampSpecified {
            get {
                return this.timestampFieldSpecified;
            }
            set {
                this.timestampFieldSpecified = value;
                this.RaisePropertyChanged("timestampSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string countryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
                this.RaisePropertyChanged("countryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string operatorCode {
            get {
                return this.operatorCodeField;
            }
            set {
                this.operatorCodeField = value;
                this.RaisePropertyChanged("operatorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string vlrGt {
            get {
                return this.vlrGtField;
            }
            set {
                this.vlrGtField = value;
                this.RaisePropertyChanged("vlrGt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=6)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.dcp.ericsson.net/SubscriptionTraffic")]
    public partial class traffic : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int returnCodeField;
        
        private string imsiField;
        
        private string msisdnField;
        
        private string imeiField;
        
        private System.DateTime sessionStartField;
        
        private bool sessionStartFieldSpecified;
        
        private lastLu lastLuField;
        
        private gprs gprsField;
        
        private sms smsMoField;
        
        private sms smsMtField;
        
        private System.DateTime lastActivityField;
        
        private bool lastActivityFieldSpecified;
        
        private System.DateTime lastSmsErrorTimeField;
        
        private bool lastSmsErrorTimeFieldSpecified;
        
        private string lastSmsErrorField;
        
        private string customerNoField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int returnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
                this.RaisePropertyChanged("returnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string imsi {
            get {
                return this.imsiField;
            }
            set {
                this.imsiField = value;
                this.RaisePropertyChanged("imsi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
                this.RaisePropertyChanged("msisdn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string imei {
            get {
                return this.imeiField;
            }
            set {
                this.imeiField = value;
                this.RaisePropertyChanged("imei");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime sessionStart {
            get {
                return this.sessionStartField;
            }
            set {
                this.sessionStartField = value;
                this.RaisePropertyChanged("sessionStart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sessionStartSpecified {
            get {
                return this.sessionStartFieldSpecified;
            }
            set {
                this.sessionStartFieldSpecified = value;
                this.RaisePropertyChanged("sessionStartSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public lastLu lastLu {
            get {
                return this.lastLuField;
            }
            set {
                this.lastLuField = value;
                this.RaisePropertyChanged("lastLu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public gprs gprs {
            get {
                return this.gprsField;
            }
            set {
                this.gprsField = value;
                this.RaisePropertyChanged("gprs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public sms smsMo {
            get {
                return this.smsMoField;
            }
            set {
                this.smsMoField = value;
                this.RaisePropertyChanged("smsMo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public sms smsMt {
            get {
                return this.smsMtField;
            }
            set {
                this.smsMtField = value;
                this.RaisePropertyChanged("smsMt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public System.DateTime lastActivity {
            get {
                return this.lastActivityField;
            }
            set {
                this.lastActivityField = value;
                this.RaisePropertyChanged("lastActivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastActivitySpecified {
            get {
                return this.lastActivityFieldSpecified;
            }
            set {
                this.lastActivityFieldSpecified = value;
                this.RaisePropertyChanged("lastActivitySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public System.DateTime lastSmsErrorTime {
            get {
                return this.lastSmsErrorTimeField;
            }
            set {
                this.lastSmsErrorTimeField = value;
                this.RaisePropertyChanged("lastSmsErrorTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastSmsErrorTimeSpecified {
            get {
                return this.lastSmsErrorTimeFieldSpecified;
            }
            set {
                this.lastSmsErrorTimeFieldSpecified = value;
                this.RaisePropertyChanged("lastSmsErrorTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string lastSmsError {
            get {
                return this.lastSmsErrorField;
            }
            set {
                this.lastSmsErrorField = value;
                this.RaisePropertyChanged("lastSmsError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string customerNo {
            get {
                return this.customerNoField;
            }
            set {
                this.customerNoField = value;
                this.RaisePropertyChanged("customerNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=13)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.dcp.ericsson.net/SubscriptionTraffic")]
    public partial class queryResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private traffic[] trafficField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("traffic", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public traffic[] traffic {
            get {
                return this.trafficField;
            }
            set {
                this.trafficField = value;
                this.RaisePropertyChanged("traffic");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class queryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.dcp.ericsson.net/SubscriptionTraffic", Order=0)]
        public EricssonConsoleApiTester.SubscriptionTraffic.query Query;
        
        public queryRequest() {
        }
        
        public queryRequest(EricssonConsoleApiTester.SubscriptionTraffic.query Query) {
            this.Query = Query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class queryResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.dcp.ericsson.net/SubscriptionTraffic", Order=0)]
        public EricssonConsoleApiTester.SubscriptionTraffic.queryResponse QueryResponse;
        
        public queryResponse1() {
        }
        
        public queryResponse1(EricssonConsoleApiTester.SubscriptionTraffic.queryResponse QueryResponse) {
            this.QueryResponse = QueryResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SubscriptionTrafficChannel : EricssonConsoleApiTester.SubscriptionTraffic.SubscriptionTraffic, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubscriptionTrafficClient : System.ServiceModel.ClientBase<EricssonConsoleApiTester.SubscriptionTraffic.SubscriptionTraffic>, EricssonConsoleApiTester.SubscriptionTraffic.SubscriptionTraffic {
        
        public SubscriptionTrafficClient() {
        }
        
        public SubscriptionTrafficClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SubscriptionTrafficClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubscriptionTrafficClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubscriptionTrafficClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EricssonConsoleApiTester.SubscriptionTraffic.queryResponse1 EricssonConsoleApiTester.SubscriptionTraffic.SubscriptionTraffic.query(EricssonConsoleApiTester.SubscriptionTraffic.queryRequest request) {
            return base.Channel.query(request);
        }
        
        public EricssonConsoleApiTester.SubscriptionTraffic.queryResponse query(EricssonConsoleApiTester.SubscriptionTraffic.query Query1) {
            EricssonConsoleApiTester.SubscriptionTraffic.queryRequest inValue = new EricssonConsoleApiTester.SubscriptionTraffic.queryRequest();
            inValue.Query = Query1;
            EricssonConsoleApiTester.SubscriptionTraffic.queryResponse1 retVal = ((EricssonConsoleApiTester.SubscriptionTraffic.SubscriptionTraffic)(this)).query(inValue);
            return retVal.QueryResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EricssonConsoleApiTester.SubscriptionTraffic.queryResponse1> EricssonConsoleApiTester.SubscriptionTraffic.SubscriptionTraffic.queryAsync(EricssonConsoleApiTester.SubscriptionTraffic.queryRequest request) {
            return base.Channel.queryAsync(request);
        }
        
        public System.Threading.Tasks.Task<EricssonConsoleApiTester.SubscriptionTraffic.queryResponse1> queryAsync(EricssonConsoleApiTester.SubscriptionTraffic.query Query) {
            EricssonConsoleApiTester.SubscriptionTraffic.queryRequest inValue = new EricssonConsoleApiTester.SubscriptionTraffic.queryRequest();
            inValue.Query = Query;
            return ((EricssonConsoleApiTester.SubscriptionTraffic.SubscriptionTraffic)(this)).queryAsync(inValue);
        }
    }
}
