//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Web.Services.Protocols;

namespace EricssonConsoleApiTester.ApiStatus {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.dcp.ericsson.net/ApiStatus", ConfigurationName="ApiStatus.ApiStatus")]
    public interface ApiStatus {
        
        // CODEGEN: Generating message contract since the operation echo is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EricssonConsoleApiTester.ApiStatus.echoResponse1 echo(EricssonConsoleApiTester.ApiStatus.echoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<EricssonConsoleApiTester.ApiStatus.echoResponse1> echoAsync(EricssonConsoleApiTester.ApiStatus.echoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.dcp.ericsson.net/ApiStatus")]
    public partial class echo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.dcp.ericsson.net/ApiStatus")]
    public partial class echoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class echoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.dcp.ericsson.net/ApiStatus", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EricssonConsoleApiTester.ApiStatus.echo Echo;
        
        public echoRequest() {
        }
        
        public echoRequest(EricssonConsoleApiTester.ApiStatus.echo Echo) {
            this.Echo = Echo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class echoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.dcp.ericsson.net/ApiStatus", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EricssonConsoleApiTester.ApiStatus.echoResponse EchoResponse;
        
        public echoResponse1() {
        }
        
        public echoResponse1(EricssonConsoleApiTester.ApiStatus.echoResponse EchoResponse) {
            this.EchoResponse = EchoResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ApiStatusChannel : EricssonConsoleApiTester.ApiStatus.ApiStatus, System.ServiceModel.IClientChannel {
    }
    
 
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApiStatusClient : System.ServiceModel.ClientBase<EricssonConsoleApiTester.ApiStatus.ApiStatus>, EricssonConsoleApiTester.ApiStatus.ApiStatus
    {

        public ApiStatusClient() {
        }
        
        public ApiStatusClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApiStatusClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiStatusClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiStatusClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]

        EricssonConsoleApiTester.ApiStatus.echoResponse1 EricssonConsoleApiTester.ApiStatus.ApiStatus.echo(EricssonConsoleApiTester.ApiStatus.echoRequest request) {
            return base.Channel.echo(request);
        }

        public EricssonConsoleApiTester.ApiStatus.echoResponse echo(EricssonConsoleApiTester.ApiStatus.echo Echo1) {
            EricssonConsoleApiTester.ApiStatus.echoRequest inValue = new EricssonConsoleApiTester.ApiStatus.echoRequest();
            inValue.Echo = Echo1;
            EricssonConsoleApiTester.ApiStatus.echoResponse1 retVal = ((EricssonConsoleApiTester.ApiStatus.ApiStatus)(this)).echo(inValue);
            return retVal.EchoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EricssonConsoleApiTester.ApiStatus.echoResponse1> EricssonConsoleApiTester.ApiStatus.ApiStatus.echoAsync(EricssonConsoleApiTester.ApiStatus.echoRequest request) {
            return base.Channel.echoAsync(request);
        }
        
        public System.Threading.Tasks.Task<EricssonConsoleApiTester.ApiStatus.echoResponse1> echoAsync(EricssonConsoleApiTester.ApiStatus.echo Echo) {
            EricssonConsoleApiTester.ApiStatus.echoRequest inValue = new EricssonConsoleApiTester.ApiStatus.echoRequest();
            inValue.Echo = Echo;
            return ((EricssonConsoleApiTester.ApiStatus.ApiStatus)(this)).echoAsync(inValue);
        }
    }
}
