//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Azure.Devices.Applications.RemoteMonitoring.DeviceAdmin.Infrastructure." +
                            "Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A physical hardware device..
        /// </summary>
        internal static string CustomDeviceDescription {
            get {
                return ResourceManager.GetString("CustomDeviceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://azure.microsoft.com/documentation/articles/iot-suite-connecting-devices/.
        /// </summary>
        internal static string CustomDeviceInstructionsUrl {
            get {
                return ResourceManager.GetString("CustomDeviceInstructionsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Device.
        /// </summary>
        internal static string CustomDeviceName {
            get {
                return ResourceManager.GetString("CustomDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device {0} is already registered..
        /// </summary>
        internal static string DeviceAlreadyRegisteredExceptionMessage {
            get {
                return ResourceManager.GetString("DeviceAlreadyRegisteredExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device {0} is not registered..
        /// </summary>
        internal static string DeviceNotRegisteredExceptionMessage {
            get {
                return ResourceManager.GetString("DeviceNotRegisteredExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while registering device {0}..
        /// </summary>
        internal static string DeviceRegistrationExceptionMessage {
            get {
                return ResourceManager.GetString("DeviceRegistrationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Enabled State must be set. Please select Enabled or Disabled..
        /// </summary>
        internal static string EnabledStateNotSetError {
            get {
                return ResourceManager.GetString("EnabledStateNotSetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software to simulate a device. Easily extensible for arbitrary events and commands; can run in a Windows Azure worker role. To create a simulated device, please follow the cooler sample instructions..
        /// </summary>
        internal static string SimulatedDeviceDescription {
            get {
                return ResourceManager.GetString("SimulatedDeviceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulated Device.
        /// </summary>
        internal static string SimulatedDeviceName {
            get {
                return ResourceManager.GetString("SimulatedDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred..
        /// </summary>
        internal static string UnexpectedErrorOccurred {
            get {
                return ResourceManager.GetString("UnexpectedErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device {0} does not support the command {1}..
        /// </summary>
        internal static string UnsupportedCommandExceptionMessage {
            get {
                return ResourceManager.GetString("UnsupportedCommandExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device already exists in the device registry.
        /// </summary>
        internal static string ValidationDeviceExists {
            get {
                return ResourceManager.GetString("ValidationDeviceExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceID cannot be empty or null.
        /// </summary>
        internal static string ValidationDeviceIdMissing {
            get {
                return ResourceManager.GetString("ValidationDeviceIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more validation errors occured for device {0}..
        /// </summary>
        internal static string ValidationExceptionMessage {
            get {
                return ResourceManager.GetString("ValidationExceptionMessage", resourceCulture);
            }
        }
    }
}
