//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EricssonConsoleApiTester.RealtimeTrace {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.dcp.ericsson.net/RealtimeTrace", ConfigurationName="RealtimeTrace.RealtimeTrace")]
    public interface RealtimeTrace {
        
        // CODEGEN: Generating message contract since the operation query is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://api.dcp.ericsson.net/RealtimeTrace/RealtimeTrace/queryRequest", ReplyAction="http://api.dcp.ericsson.net/RealtimeTrace/RealtimeTrace/queryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EricssonConsoleApiTester.RealtimeTrace.queryResponse1 query(EricssonConsoleApiTester.RealtimeTrace.queryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.dcp.ericsson.net/RealtimeTrace/RealtimeTrace/queryRequest", ReplyAction="http://api.dcp.ericsson.net/RealtimeTrace/RealtimeTrace/queryResponse")]
        System.Threading.Tasks.Task<EricssonConsoleApiTester.RealtimeTrace.queryResponse1> queryAsync(EricssonConsoleApiTester.RealtimeTrace.queryRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://api.dcp.ericsson.net/RealtimeTrace")]
    public partial class Query : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customernoField;
        
        private int traceLengthField;
        
        private Filter filterField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string customerno {
            get {
                return this.customernoField;
            }
            set {
                this.customernoField = value;
                this.RaisePropertyChanged("customerno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int traceLength {
            get {
                return this.traceLengthField;
            }
            set {
                this.traceLengthField = value;
                this.RaisePropertyChanged("traceLength");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public Filter filter {
            get {
                return this.filterField;
            }
            set {
                this.filterField = value;
                this.RaisePropertyChanged("filter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=3)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.dcp.ericsson.net/RealtimeTrace")]
    public partial class Filter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResourceFilter resourceFilterField;
        
        private EventFilter eventFilterField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResourceFilter resourceFilter {
            get {
                return this.resourceFilterField;
            }
            set {
                this.resourceFilterField = value;
                this.RaisePropertyChanged("resourceFilter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public EventFilter eventFilter {
            get {
                return this.eventFilterField;
            }
            set {
                this.eventFilterField = value;
                this.RaisePropertyChanged("eventFilter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.dcp.ericsson.net/RealtimeTrace")]
    public partial class ResourceFilter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resourceTypeField;
        
        private string resourceIdField;
        
        private int rangeField;
        
        private bool rangeFieldSpecified;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string resourceType {
            get {
                return this.resourceTypeField;
            }
            set {
                this.resourceTypeField = value;
                this.RaisePropertyChanged("resourceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string resourceId {
            get {
                return this.resourceIdField;
            }
            set {
                this.resourceIdField = value;
                this.RaisePropertyChanged("resourceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int range {
            get {
                return this.rangeField;
            }
            set {
                this.rangeField = value;
                this.RaisePropertyChanged("range");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rangeSpecified {
            get {
                return this.rangeFieldSpecified;
            }
            set {
                this.rangeFieldSpecified = value;
                this.RaisePropertyChanged("rangeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=3)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.dcp.ericsson.net/RealtimeTrace")]
    public partial class TraceData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime timeStampField;
        
        private bool timeStampFieldSpecified;
        
        private string imsiField;
        
        private string originatingMsisdnField;
        
        private string terminatingMsisdnField;
        
        private string eventField;
        
        private string countryCodeField;
        
        private string operatorCodeField;
        
        private string hlrgtField;
        
        private string vlrgtField;
        
        private string ggsnipField;
        
        private string sgsnipField;
        
        private int gtpCauseField;
        
        private bool gtpCauseFieldSpecified;
        
        private string gprsTeidField;
        
        private string smsReportField;
        
        private string mapStatusField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime timeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("timeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeStampSpecified {
            get {
                return this.timeStampFieldSpecified;
            }
            set {
                this.timeStampFieldSpecified = value;
                this.RaisePropertyChanged("timeStampSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string imsi {
            get {
                return this.imsiField;
            }
            set {
                this.imsiField = value;
                this.RaisePropertyChanged("imsi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string originatingMsisdn {
            get {
                return this.originatingMsisdnField;
            }
            set {
                this.originatingMsisdnField = value;
                this.RaisePropertyChanged("originatingMsisdn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string terminatingMsisdn {
            get {
                return this.terminatingMsisdnField;
            }
            set {
                this.terminatingMsisdnField = value;
                this.RaisePropertyChanged("terminatingMsisdn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string @event {
            get {
                return this.eventField;
            }
            set {
                this.eventField = value;
                this.RaisePropertyChanged("event");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string countryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
                this.RaisePropertyChanged("countryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string operatorCode {
            get {
                return this.operatorCodeField;
            }
            set {
                this.operatorCodeField = value;
                this.RaisePropertyChanged("operatorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string hlrgt {
            get {
                return this.hlrgtField;
            }
            set {
                this.hlrgtField = value;
                this.RaisePropertyChanged("hlrgt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string vlrgt {
            get {
                return this.vlrgtField;
            }
            set {
                this.vlrgtField = value;
                this.RaisePropertyChanged("vlrgt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ggsnip {
            get {
                return this.ggsnipField;
            }
            set {
                this.ggsnipField = value;
                this.RaisePropertyChanged("ggsnip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string sgsnip {
            get {
                return this.sgsnipField;
            }
            set {
                this.sgsnipField = value;
                this.RaisePropertyChanged("sgsnip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int gtpCause {
            get {
                return this.gtpCauseField;
            }
            set {
                this.gtpCauseField = value;
                this.RaisePropertyChanged("gtpCause");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gtpCauseSpecified {
            get {
                return this.gtpCauseFieldSpecified;
            }
            set {
                this.gtpCauseFieldSpecified = value;
                this.RaisePropertyChanged("gtpCauseSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string gprsTeid {
            get {
                return this.gprsTeidField;
            }
            set {
                this.gprsTeidField = value;
                this.RaisePropertyChanged("gprsTeid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string smsReport {
            get {
                return this.smsReportField;
            }
            set {
                this.smsReportField = value;
                this.RaisePropertyChanged("smsReport");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string mapStatus {
            get {
                return this.mapStatusField;
            }
            set {
                this.mapStatusField = value;
                this.RaisePropertyChanged("mapStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=15)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.dcp.ericsson.net/RealtimeTrace")]
    public partial class Events : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] eventField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("event", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string[] @event {
            get {
                return this.eventField;
            }
            set {
                this.eventField = value;
                this.RaisePropertyChanged("event");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.dcp.ericsson.net/RealtimeTrace")]
    public partial class EventFilter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string countryCodeField;
        
        private string operatorCodeField;
        
        private Events eventListField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string countryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
                this.RaisePropertyChanged("countryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string operatorCode {
            get {
                return this.operatorCodeField;
            }
            set {
                this.operatorCodeField = value;
                this.RaisePropertyChanged("operatorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public Events eventList {
            get {
                return this.eventListField;
            }
            set {
                this.eventListField = value;
                this.RaisePropertyChanged("eventList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=3)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://api.dcp.ericsson.net/RealtimeTrace")]
    public partial class QueryResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TraceData[] traceDataField;
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("traceData", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public TraceData[] traceData {
            get {
                return this.traceDataField;
            }
            set {
                this.traceDataField = value;
                this.RaisePropertyChanged("traceData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class queryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.dcp.ericsson.net/RealtimeTrace", Order=0)]
        public EricssonConsoleApiTester.RealtimeTrace.Query Query;
        
        public queryRequest() {
        }
        
        public queryRequest(EricssonConsoleApiTester.RealtimeTrace.Query Query) {
            this.Query = Query;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class queryResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.dcp.ericsson.net/RealtimeTrace", Order=0)]
        public EricssonConsoleApiTester.RealtimeTrace.QueryResponse QueryResponse;
        
        public queryResponse1() {
        }
        
        public queryResponse1(EricssonConsoleApiTester.RealtimeTrace.QueryResponse QueryResponse) {
            this.QueryResponse = QueryResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RealtimeTraceChannel : EricssonConsoleApiTester.RealtimeTrace.RealtimeTrace, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RealtimeTraceClient : System.ServiceModel.ClientBase<EricssonConsoleApiTester.RealtimeTrace.RealtimeTrace>, EricssonConsoleApiTester.RealtimeTrace.RealtimeTrace {
        
        public RealtimeTraceClient() {
        }
        
        public RealtimeTraceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RealtimeTraceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealtimeTraceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealtimeTraceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EricssonConsoleApiTester.RealtimeTrace.queryResponse1 EricssonConsoleApiTester.RealtimeTrace.RealtimeTrace.query(EricssonConsoleApiTester.RealtimeTrace.queryRequest request) {
            return base.Channel.query(request);
        }
        
        public EricssonConsoleApiTester.RealtimeTrace.QueryResponse query(EricssonConsoleApiTester.RealtimeTrace.Query Query1) {
            EricssonConsoleApiTester.RealtimeTrace.queryRequest inValue = new EricssonConsoleApiTester.RealtimeTrace.queryRequest();
            inValue.Query = Query1;
            EricssonConsoleApiTester.RealtimeTrace.queryResponse1 retVal = ((EricssonConsoleApiTester.RealtimeTrace.RealtimeTrace)(this)).query(inValue);
            return retVal.QueryResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EricssonConsoleApiTester.RealtimeTrace.queryResponse1> EricssonConsoleApiTester.RealtimeTrace.RealtimeTrace.queryAsync(EricssonConsoleApiTester.RealtimeTrace.queryRequest request) {
            return base.Channel.queryAsync(request);
        }
        
        public System.Threading.Tasks.Task<EricssonConsoleApiTester.RealtimeTrace.queryResponse1> queryAsync(EricssonConsoleApiTester.RealtimeTrace.Query Query) {
            EricssonConsoleApiTester.RealtimeTrace.queryRequest inValue = new EricssonConsoleApiTester.RealtimeTrace.queryRequest();
            inValue.Query = Query;
            return ((EricssonConsoleApiTester.RealtimeTrace.RealtimeTrace)(this)).queryAsync(inValue);
        }
    }
}
