//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceManagement.Infrustructure.Connectivity.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api7.jasperwireless.com/ws/service/billing")]
        public string DeviceManagement_Infrustructure_Connectivity_com_jasperwireless_spark_BillingService {
            get {
                return ((string)(this["DeviceManagement_Infrustructure_Connectivity_com_jasperwireless_spark_BillingServ" +
                    "ice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api7.jasperwireless.com/ws/service/terminal")]
        public string DeviceManagement_Infrustructure_Connectivity_com_jasperwireless_spark_terminal_TerminalService {
            get {
                return ((string)(this["DeviceManagement_Infrustructure_Connectivity_com_jasperwireless_spark_terminal_Te" +
                    "rminalService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api7.jasperwireless.com/ws/service/echo")]
        public string DeviceManagement_Infrustructure_Connectivity_com_jasperwireless_spark_echo_EchoService {
            get {
                return ((string)(this["DeviceManagement_Infrustructure_Connectivity_com_jasperwireless_spark_echo_EchoSe" +
                    "rvice"]));
            }
        }
    }
}
