//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceManagement.Infrustructure.Connectivity.EricssonApiService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.dcp.ericsson.net/ApiStatus", ConfigurationName="EricssonApiService.ApiStatus")]
    public interface ApiStatus {
        
        // CODEGEN: Generating message contract since the operation echo is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DeviceManagement.Infrustructure.Connectivity.EricssonApiService.echoResponse1 echo(DeviceManagement.Infrustructure.Connectivity.EricssonApiService.echoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<DeviceManagement.Infrustructure.Connectivity.EricssonApiService.echoResponse1> echoAsync(DeviceManagement.Infrustructure.Connectivity.EricssonApiService.echoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.dcp.ericsson.net/ApiStatus")]
    public partial class echo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://api.dcp.ericsson.net/ApiStatus")]
    public partial class echoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class echoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.dcp.ericsson.net/ApiStatus", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DeviceManagement.Infrustructure.Connectivity.EricssonApiService.echo Echo;
        
        public echoRequest() {
        }
        
        public echoRequest(DeviceManagement.Infrustructure.Connectivity.EricssonApiService.echo Echo) {
            this.Echo = Echo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class echoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://api.dcp.ericsson.net/ApiStatus", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DeviceManagement.Infrustructure.Connectivity.EricssonApiService.echoResponse EchoResponse;
        
        public echoResponse1() {
        }
        
        public echoResponse1(DeviceManagement.Infrustructure.Connectivity.EricssonApiService.echoResponse EchoResponse) {
            this.EchoResponse = EchoResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ApiStatusChannel : DeviceManagement.Infrustructure.Connectivity.EricssonApiService.ApiStatus, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApiStatusClient : System.ServiceModel.ClientBase<DeviceManagement.Infrustructure.Connectivity.EricssonApiService.ApiStatus>, DeviceManagement.Infrustructure.Connectivity.EricssonApiService.ApiStatus {
        
        public ApiStatusClient() {
        }
        
        public ApiStatusClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApiStatusClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiStatusClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApiStatusClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DeviceManagement.Infrustructure.Connectivity.EricssonApiService.echoResponse1 DeviceManagement.Infrustructure.Connectivity.EricssonApiService.ApiStatus.echo(DeviceManagement.Infrustructure.Connectivity.EricssonApiService.echoRequest request) {
            return base.Channel.echo(request);
        }
        
        public DeviceManagement.Infrustructure.Connectivity.EricssonApiService.echoResponse echo(DeviceManagement.Infrustructure.Connectivity.EricssonApiService.echo Echo1) {
            DeviceManagement.Infrustructure.Connectivity.EricssonApiService.echoRequest inValue = new DeviceManagement.Infrustructure.Connectivity.EricssonApiService.echoRequest();
            inValue.Echo = Echo1;
            DeviceManagement.Infrustructure.Connectivity.EricssonApiService.echoResponse1 retVal = ((DeviceManagement.Infrustructure.Connectivity.EricssonApiService.ApiStatus)(this)).echo(inValue);
            return retVal.EchoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DeviceManagement.Infrustructure.Connectivity.EricssonApiService.echoResponse1> DeviceManagement.Infrustructure.Connectivity.EricssonApiService.ApiStatus.echoAsync(DeviceManagement.Infrustructure.Connectivity.EricssonApiService.echoRequest request) {
            return base.Channel.echoAsync(request);
        }
        
        public System.Threading.Tasks.Task<DeviceManagement.Infrustructure.Connectivity.EricssonApiService.echoResponse1> echoAsync(DeviceManagement.Infrustructure.Connectivity.EricssonApiService.echo Echo) {
            DeviceManagement.Infrustructure.Connectivity.EricssonApiService.echoRequest inValue = new DeviceManagement.Infrustructure.Connectivity.EricssonApiService.echoRequest();
            inValue.Echo = Echo;
            return ((DeviceManagement.Infrustructure.Connectivity.EricssonApiService.ApiStatus)(this)).echoAsync(inValue);
        }
    }
}
